"""A follow-up without shared keywords still needs the preceding exchange."""
from cain.common import Signal
from cain.runtime import build_cain
from cain.orchestrator import RuleRouter


def remember(runtime, user, session, project, text, marker):
    runtime.identity.update(user, Signal(text, metadata={
        'user_input':text,'preference_observed':True,'session_id':session,
        'project_id':project,'decision_id':marker,
    }))


def test_recent_exchange_survives_no_keyword_overlap_and_restart(tmp_path):
    path=tmp_path/'memory.db'
    with build_cain(path) as runtime:
        remember(runtime,'alice','s','p','Cedro custa 12 reais; pinho custa 8 reais.','a')
    with build_cain(path) as reopened:
        context=reopened.identity.context_for('alice','Explique melhor.',project_id='p',session_id='s')
        assert 'Cedro custa 12' in context and 'pinho custa 8' in context
        assert len(context.encode()) <= reopened.identity.max_context_bytes


def test_recent_exchange_does_not_cross_scope_or_restore_preferences(tmp_path):
    with build_cain(tmp_path/'memory.db') as runtime:
        for user,session,project,text in [
            ('alice','s','p','VISIBLE_CONTEXT'),('bob','s','p','OTHER_USER'),
            ('alice','s','q','OTHER_PROJECT'),('alice','t','p','OTHER_SESSION'),
            ('alice','s','p','Prefiro respostas em passos. OLD_PREFERENCE'),
        ]:
            remember(runtime,user,session,project,text,text)
        context=runtime.identity.context_for('alice','Explique melhor.',project_id='p',session_id='s')
        assert 'VISIBLE_CONTEXT' in context
        for hidden in ('OTHER_USER','OTHER_PROJECT','OTHER_SESSION','OLD_PREFERENCE'):
            assert hidden not in context


def test_followup_uses_recent_context_without_reclassifying_as_document_search(tmp_path):
    class Model:
        def generate(self, prompt, context=''):
            assert 'pinho custa 8' in context
            return 'Pinho custa menos: a diferença é 4 reais.'

        def generate_json(self, *args):
            raise AssertionError('Known conversational follow-up needs no model classifier')

    with build_cain(tmp_path/'conversation.db', Model(), router=RuleRouter(Model())) as runtime:
        remember(runtime,'alice','s',None,'Cedro custa 12 reais; pinho custa 8 reais.','a')
        result=runtime.run('alice','s','Qual das duas opções custa menos?')
        assert result.selected_agent=='conversa'
        assert 'diferença é 4' in result.response
        assert list(runtime.decision_log.export(result.run_id))[0].reason=='conversation_rule:followup'


def test_explicit_conversation_is_real_provider_path_even_for_social_messages(tmp_path):
    class Model:
        def __init__(self):
            self.calls=[]

        def generate(self,prompt,context=''):
            self.calls.append(prompt)
            return 'Generated by the selected provider'

    model=Model()
    with build_cain(tmp_path/'explicit.db',model) as runtime:
        result=runtime.run('qa','s','Tudo bem?',intent='conversa')
    assert model.calls==['Tudo bem?']
    assert result.response=='Generated by the selected provider'


def test_unrelated_old_conversation_is_not_prompt_context_from_stopwords(tmp_path):
    with build_cain(tmp_path/'irrelevant.db') as runtime:
        remember(runtime,'qa','old',None,'O código é JADE731.','a')
        context=runtime.identity.context_for('qa','O que é nebulosa ZXQ987?',session_id='new')
        assert 'JADE731' not in context


def test_output_instructions_do_not_retrieve_unrelated_previous_answers(tmp_path):
    with build_cain(tmp_path/'instructions.db') as runtime:
        remember(runtime,'qa','old',None,'Responda somente: CAIN QA\nCain: CAIN QA','a')
        context=runtime.identity.context_for(
            'qa','O relatório autoriza o lançamento? Responda em uma frase.',session_id='new')
        assert 'CAIN QA' not in context


def test_selected_recent_exchanges_are_presented_in_conversation_order(tmp_path):
    with build_cain(tmp_path/'chronology.db') as runtime:
        remember(runtime,'qa','s',None,'OLDER_GREETING','a')
        remember(runtime,'qa','s',None,'LATEST_PRICES','b')
        context=runtime.identity.context_for('qa','Explique melhor.',session_id='s')
        assert context.index('OLDER_GREETING') < context.index('LATEST_PRICES')


def test_one_sentence_request_does_not_erase_facts_for_followup(tmp_path):
    class Model:
        def generate(self, prompt, context=''):
            if prompt.startswith('Explique melhor.'):
                assert '37 reais' in context and '24 reais' in context
            return 'A diferença é 13 reais.'

        def generate_json(self, *args):
            raise AssertionError('The factual episode must remain available for follow-up')

    model = Model()
    with build_cain(tmp_path/'one-sentence.db', model, router=RuleRouter(model)) as runtime:
        runtime.run('qa', 's', 'Vamos comparar planos fictícios: A custa 37 reais e B custa 24 reais. '
                    'Responda em uma frase.')
        assert runtime.identity.get('qa').user_model.preferences == {}
        result = runtime.run('qa', 's', 'Explique melhor.')
        assert result.selected_agent == 'conversa'
