"""The three persistence ports from ADR-0009, independent of storage backends."""

from collections.abc import Iterable
from typing import Protocol, runtime_checkable

from cain.common import DecisionRecord, Hit, IdentitySnapshot, IdentityState, MemoryDocument, Signal


@runtime_checkable
class IdentityStore(Protocol):
    def get(self, user_id: str) -> IdentityState | None: ...
    def upsert(self, user_id: str, state: IdentityState) -> None: ...
    def append_signal(self, user_id: str, signal: Signal) -> None: ...
    def history(self, user_id: str, limit: int) -> list[IdentitySnapshot]: ...
    # Engineering extension: ADR-0009 has no enumeration method. Rebuild requires
    # the authoritative documents, including their stable ids and user ownership.
    def iter_documents(self) -> Iterable[MemoryDocument]: ...


@runtime_checkable
class MemoryIndex(Protocol):
    def index(self, doc_id: str, text: str, metadata: dict) -> None: ...
    def query(self, text: str, k: int, filters: dict | None = None) -> list[Hit]: ...
    def rebuild_from(self, source: IdentityStore) -> None: ...
    def drop(self) -> None: ...


@runtime_checkable
class DecisionLog(Protocol):
    def append(self, record: DecisionRecord) -> None: ...
    def export(self, run_id: str) -> Iterable[DecisionRecord]: ...
